#!/usr/bin/env perl
use v5.10;
use strict;
use warnings;
use autodie qw/:all/;
use Getopt::Long;

my $as;
my $threads;
my ($dist,@dist);

GetOptions ("as=s"     => \$as,        # string
            "dist:s"   => \$dist,      # string (optional)
            "threads"  => \$threads)   # flag
or die("Error in command line arguments\n");

unless ($as) {
  die "Usage: $0 --as=<perl-version> [--dist=/path/to/perl.tar.gz] [--threads]";
}

if ($dist) {
  my $dist_path = 
    "$ENV{HOME}/perl5/perlbrew/dists/${dist}";
  if (-f $dist_path) {
    @dist = ( $dist_path );
  } else {
    die "Specified dist $dist_path doesn't exist";
  }
} else { @dist = (); }
my @args = @ARGV;
 
# --threads means do threads
my @threads = ( $threads ) ? (qw/-D usethreads/) : ();
 
$as =~ s/^5\.//;
my $perl = "5.$as";
$perl =~ s/t$//; # strip trailing "t" if any
my $lib = $as . '@std';

# Test::Base needs gmake! 
my @problem_modules = qw(
  JSON::XS
  IPC::Run
);
 
  # Task::BeLike::DAGOLDEN
my @to_install = qw(
Algorithm::C3
Algorithm::Diff
Algorithm::Diff::Callback
Any::Moose
AnyEvent
AnyEvent::HTTP
Apache::Htpasswd
Apache::LogFormat::Compiler
App::Cmd
App::cpanminus
App::perlbrew
AppConfig
Archive::Any
Archive::Any::Create
Archive::Extract
Archive::Tar
Archive::Zip
Authen::Simple
Authen::Simple::Passwd
B::Hooks::EndOfScope
B::Hooks::OP::Check
B::Keywords
B::Utils
Bit::Vector
CGI::Compile
CGI::Emulate::PSGI
CGI::PSGI
CGI::Simple
CGI::Struct
CLASS
CPAN::Checksums
CPAN::DistnameInfo
CPAN::Meta
CPAN::Meta::Check
CPAN::Meta::YAML
CPAN::Mini
CPAN::Perl::Releases
CPAN::Uploader
Cache::Cache
Cache::FastMmap
Carp::Always
Carp::Assert
Carp::Assert::More
Carp::Clan
Carp::Clan::Share
Carp::REPL
Catalyst::Action::RenderView
Catalyst::Authentication::Store::DBIx::Class
Catalyst::Component::InstancePerContext
Catalyst::Controller::HTML::FormFu
Catalyst::Devel
Catalyst::DispatchType::Regex
Catalyst::Manual
Catalyst::Model::DBIC::Schema
Catalyst::Plugin::Authentication
Catalyst::Plugin::Authorization::ACL
Catalyst::Plugin::Authorization::Roles
Catalyst::Plugin::ConfigLoader
Catalyst::Plugin::Log::Log4perl
Catalyst::Plugin::LogDeep
Catalyst::Plugin::LogWarnings
Catalyst::Plugin::Session
Catalyst::Plugin::Session::State::Cookie
Catalyst::Plugin::Session::Store::FastMmap
Catalyst::Plugin::Session::Store::File
Catalyst::Plugin::StackTrace
Catalyst::Plugin::Static::Simple
Catalyst::Plugin::Unicode
Catalyst::Runtime
Catalyst::View::JSON
Catalyst::View::TT
CatalystX::Component::Traits
CatalystX::REPL
Class::Accessor
Class::Accessor::Chained
Class::Accessor::Grouped
Class::Accessor::Lite
Class::C3
Class::C3::Adopt::NEXT
Class::C3::Componentised
Class::Data::Inheritable
Class::Factory::Util
Class::Inspector
Class::Iterator
Class::Load
Class::Load::XS
Class::Method::Modifiers
Class::Singleton
Class::Throwable
Class::Tiny
Class::Unload
Class::XSAccessor
Clone
Compress::Bzip2
Config::Any
Config::General
Config::INI
Config::JFDI
Config::MVP
Config::MVP::Reader::INI
Config::MVP::Slicer
Config::MySQL
Config::Tiny
Context::Preserve
Convert::ASN1
Coro
Corona
Cpanel::JSON::XS
Crypt::Blowfish
Crypt::CAST5
Crypt::CBC
Crypt::DES
Crypt::DES_EDE3
Crypt::DH
Crypt::DSA
Crypt::IDEA
Crypt::OpenSSL::AES
Crypt::OpenSSL::DSA
Crypt::OpenSSL::RSA
Crypt::OpenSSL::Random
Crypt::PasswdMD5
Cwd::Guard
DBD::Pg
DBD::SQLite
DBI
DBICx::TestDatabase
DBIx::Class
DBIx::Class::Candy
DBIx::Class::DeploymentHandler
DBIx::Class::DynamicDefault
DBIx::Class::EncodedColumn
DBIx::Class::Fixtures
DBIx::Class::Helpers
DBIx::Class::InflateColumn::FS
DBIx::Class::IntrospectableM2M
DBIx::Class::Migration
DBIx::Class::Schema::Loader
DBIx::Class::Schema::PopulateMore
DBIx::Class::TimeStamp
DBIx::Class::UUIDColumns
DBIx::Introspector
DBM::Deep
Data::Buffer
Data::Compare
Data::Dump
Data::Dump::Streamer
Data::Dumper::Concise
Data::OptList
Data::Page
Data::Section
Data::UUID
Data::Visitor
Date::Calc
Date::Manip
Date::Parse
Date::Simple
DateTime
DateTime::Event::ICal
DateTime::Event::Recurrence
DateTime::Format::Builder
DateTime::Format::Duration
DateTime::Format::Flexible
DateTime::Format::ICal
DateTime::Format::ISO8601
DateTime::Format::MySQL
DateTime::Format::Natural
DateTime::Format::Pg
DateTime::Format::RFC3501
DateTime::Format::SQLite
DateTime::Format::Strptime
DateTime::Locale
DateTime::Moonpig
DateTime::Set
DateTime::TimeZone
DateTimeX::Easy
Devel::Caller
Devel::CheckCompiler
Devel::CheckLib
Devel::Cycle
Devel::FindPerl
Devel::GlobalDestruction
Devel::Leak
Devel::LexAlias
Devel::Mallinfo
Devel::NYTProf
Devel::PartialDump
Devel::PatchPerl
Devel::REPL
Devel::StackTrace
Devel::StackTrace::AsHTML
Devel::StackTrace::WithLexicals
Devel::Symdump
Digest::HMAC
Digest::MD5
Digest::SHA
Digest::SHA1
Dir::Self
Directory::Scratch
Dist::CheckConflicts
Dist::Metadata
Dist::Zilla
Dist::Zilla::Plugin::Authority
Dist::Zilla::Plugin::AutoMetaResources
Dist::Zilla::Plugin::CheckChangesHasContent
Dist::Zilla::Plugin::CheckExtraTests
Dist::Zilla::Plugin::CheckMetaResources
Dist::Zilla::Plugin::Config::Git
Dist::Zilla::Plugin::ContributorsFromGit
Dist::Zilla::Plugin::CopyFilesFromBuild
Dist::Zilla::Plugin::Git
Dist::Zilla::Plugin::GitFmtChanges
Dist::Zilla::Plugin::GitObtain
Dist::Zilla::Plugin::Inject
Dist::Zilla::Plugin::InsertCopyright
Dist::Zilla::Plugin::MakeMaker::Awesome
Dist::Zilla::Plugin::MetaProvides
Dist::Zilla::Plugin::MetaProvides::Package
Dist::Zilla::Plugin::MinimumPerl
Dist::Zilla::Plugin::ModuleInstall
Dist::Zilla::Plugin::OurPkgVersion
Dist::Zilla::Plugin::PerlTidy
Dist::Zilla::Plugin::Pinto::Add
Dist::Zilla::Plugin::PodWeaver
Dist::Zilla::Plugin::Prereqs::AuthorDeps
Dist::Zilla::Plugin::PromptIfStale
Dist::Zilla::Plugin::PurePerlTests
Dist::Zilla::Plugin::ReadmeAnyFromPod
Dist::Zilla::Plugin::Rsync
Dist::Zilla::Plugin::Signature
Dist::Zilla::Plugin::TaskWeaver
Dist::Zilla::Plugin::Test::CheckChanges
Dist::Zilla::Plugin::Test::CheckDeps
Dist::Zilla::Plugin::Test::CheckManifest
Dist::Zilla::Plugin::Test::Compile
Dist::Zilla::Plugin::Test::LocalBrew
Dist::Zilla::Plugin::Test::MinimumVersion
Dist::Zilla::Plugin::Test::Perl::Critic
Dist::Zilla::Plugin::Test::Pod::LinkCheck
Dist::Zilla::Plugin::Test::PodSpelling
Dist::Zilla::Plugin::Test::Portability
Dist::Zilla::Plugin::Test::ReportPrereqs
Dist::Zilla::Plugin::Test::Version
Dist::Zilla::Plugin::UploadToSFTP
Dist::Zilla::Plugin::Version::Git::Flowish
Dist::Zilla::Plugin::VersionFromScript
Dist::Zilla::Role::DynamicConfig
Dist::Zilla::Role::File::ChangeNotification
Dist::Zilla::Role::PluginBundle::PluginRemover
Dist::Zilla::Role::RegisterStash
Dist::Zilla::Role::Stash::Plugins
Dist::Zilla::Role::Tempdir
Dist::Zilla::Stash::PodWeaver
Dist::Zilla::Util::Test::KENTNL
Email::Address
Email::Valid
Encode::Locale
Error
Eval::Closure
Excel::Writer::XLSX
Exception::Class
Expect
Expect::Simple
Exporter::Declare
Exporter::Lite
Exporter::Tidy
Exporter::Tiny
ExtUtils::Config
ExtUtils::Depends
ExtUtils::Helpers
ExtUtils::InstallPaths
ExtUtils::ModuleMaker
ExtUtils::ParseXS
FCGI
FCGI::Client
FCGI::ProcManager
Fennec::Lite
File::ChangeNotify
File::Copy::Recursive
File::Find::Iterator
File::Find::Rule
File::Find::Rule::Perl
File::HomeDir
File::Listing
File::MMagic
File::NFSLock
File::Next
File::Remove
File::Save::Home
File::ShareDir
File::ShareDir::Install
File::ShareDir::ProjectDistDir
File::Slurp
File::Spec::Native
File::Temp
File::Tempdir
File::Which
File::chdir
File::pushd
Filesys::Notify::Simple
Future
Getopt::Long::Descriptive
Getopt::Usaginator
Git::Wrapper
Graph
Guard
HTML::Entities::Numbered
HTML::Form
HTML::FormFu
HTML::Parser
HTML::Scrubber
HTML::Tagset
HTML::TokeParser::Simple
HTML::Tree
HTTP::Body
HTTP::Cookies
HTTP::Daemon
HTTP::Date
HTTP::Message
HTTP::Negotiate
HTTP::Parser::XS
HTTP::Request::AsCGI
HTTP::Server::Simple
HTTP::Server::Simple::PSGI
HTTP::Tiny
Hash::FieldHash
Hash::Flatten
Hash::Merge
Hash::Merge::Simple
Hash::MultiValue
Hook::LexWrap
IO::All
IO::CaptureOutput
IO::HTML
IO::Handle::Util
IO::Interactive
IO::Prompt
IO::Socket::SSL
IO::String
IO::Stringy
IO::TieCombine
IO::Tty
IPC::Run3
IPC::System::Simple
Import::Into
JSON
JSON::Diffable
JSON::Any
JSON::MaybeXS
JSON::XS
JavaScript::Value::Escape
LWP
LWP::MediaTypes
LWP::Protocol::https
Lexical::Persistence
Lexical::SealRequireHints
Lingua::EN::FindNumber
Lingua::EN::Inflect
Lingua::EN::Inflect::Number
Lingua::EN::Inflect::Phrase
Lingua::EN::Number::IsOrdinal
Lingua::EN::Tagger
Lingua::EN::Words2Nums
Lingua::PT::Stemmer
Lingua::Stem
Lingua::Stem::Fr
Lingua::Stem::It
Lingua::Stem::Ru
Lingua::Stem::Snowball::Da
Lingua::Stem::Snowball::No
Lingua::Stem::Snowball::Se
List::AllUtils
List::MoreUtils
List::Util
Log::Contextual
Log::Deep
Log::Dispatch
Log::Dispatch::Array
Log::Dispatch::FileRotate
Log::Dispatchouli
Log::Log4perl
Log::Message::Simple
Log::Trace
MIME::Types
MLDBM
MRO::Compat
Memoize::ExpireLRU
Meta::Builder
Mixin::Linewise
Mock::Quick
Modern::Perl
Module::Build::CleanInstall
Module::Build::XSUtil
Module::CoreList
Module::Faker
Module::Find
Module::Implementation
Module::Path
Module::Pluggable
Module::ScanDeps
Module::Signature
Module::Util
Moo
MooX::Struct
MooX::Types::MooseLike
Moose
Moose::Autobox
MooseX::Aliases
MooseX::Attribute::Chained
MooseX::Attribute::ENV
MooseX::AttributeShortcuts
MooseX::ClassAttribute
MooseX::Configuration
MooseX::Daemonize
MooseX::Emulate::Class::Accessor::Fast
MooseX::Getopt
MooseX::Has::Sugar
MooseX::LazyRequire
MooseX::Log::Log4perl
MooseX::MarkAsMethods
MooseX::MethodAttributes
MooseX::NonMoose
MooseX::Object::Pluggable
MooseX::OneArgNew
MooseX::Params::Validate
MooseX::Role::Parameterized
MooseX::Role::WithOverloading
MooseX::SemiAffordanceAccessor
MooseX::SetOnce
MooseX::StrictConstructor
MooseX::Traits::Pluggable
MooseX::Types
MooseX::Types::Common
MooseX::Types::LoadableClass
MooseX::Types::Path::Class
MooseX::Types::Perl
MooseX::Types::URI
Mouse
Mozilla::CA
Net::CIDR
Net::DNS
Net::FastCGI
Net::HTTP
Net::IP
Net::SFTP::Foreign
Net::Server::Coro
NetAddr::IP
Number::Compare
Number::Format
Number::Range
Object::ID
Object::Remote
Object::Signature
PAR::Dist
POSIX::RT::Timer
PPI
PPIx::EditorTools
PPIx::Regexp
PPIx::Utilities
PSGI
Package::DeprecationManager
Package::Locator
Package::Pkg
Package::Stash
Package::Stash::XS
Package::Variant
PadWalker
Parallel::ForkManager
Parallel::Prefork
Params::Util
Params::Validate
Parse::CPAN::Meta
Parse::CPAN::Packages::Fast
Parse::RecDescent
Path::Class
Path::FindDev
Path::IsDev
Path::Iterator::Rule
Path::Tiny
Perl::Critic
Perl::MinimumVersion
Perl::PrereqScanner
Perl::Tidy
Perl::Version
Plack
Plack::App::Proxy
Plack::Middleware::Auth::Digest
Plack::Middleware::ConsoleLogger
Plack::Middleware::Debug
Plack::Middleware::Deflater
Plack::Middleware::Header
Plack::Middleware::ReverseProxy
Plack::Test::ExternalServer
Pod::Coverage
Pod::Coverage::TrustPod
Pod::Elemental
Pod::Elemental::PerlMunger
Pod::Eventual
Pod::Markdown
Pod::Spell
Pod::Weaver
Probe::Perl
Proc::Fork
Proc::Terminator
Proc::Wait3
Readonly
Readonly::XS
Regexp::Common
Regexp::Common::time
Regexp::Debugger
Role::HasMessage
Role::Identifiable::HasIdent
Role::Tiny
Router::Simple
SQL::Abstract
SQL::Translator
SVG::TT::Graph
Safe::Isa
Scalar::Does
Scope::Guard
Server::Starter
Set::Infinite
Set::Object
Set::Scalar
Software::License
Sort::Versions
Spiffy
Starlet
Starman
Storable
Stream::Buffered
String::CamelCase
String::Errf
String::Flogger
String::Format
String::Formatter
String::PerlIdentifier
String::RewritePrefix
String::ShellQuote
String::ToIdentifier::EN
String::Truncate
Sub::Attribute
Sub::Exporter
Sub::Exporter::ForMethods
Sub::Exporter::GlobExporter
Sub::Exporter::Progressive
Sub::Identify
Sub::Install
Sub::Name
Sub::Override
Sub::Uplevel
Syntax::Keyword::Junction
TAP::Stream
Task::Catalyst::Tutorial
Task::Weaken
Template
Template::Timer
Term::EditorEdit
Term::Encoding
Term::ReadKey
Term::ReadLine
Term::Size
Term::UI
Test::Aggregate
Test::Assertions
Test::Base
Test::CPAN::Meta
Test::CheckChanges
Test::CheckDeps
Test::CheckManifest
Test::Class
Test::Cmd
Test::Deep
Test::Deep::JSON
Test::Differences
Test::Effects
Test::Exception
Test::Exception::LessClever
Test::Expect
Test::FailWarnings
Test::Fatal
Test::File
Test::File::ShareDir
Test::Filename
Test::Harness
Test::HexString
Test::Identity
Test::Inter
Test::LWP::UserAgent
Test::LeakTrace
Test::LongString
Test::Manifest
Test::Memory::Cycle
Test::MinimumVersion
Test::MockObject
Test::MockTime
Test::Most
Test::NoTabs
Test::NoWarnings
Test::Object
Test::Output
Test::Perl::Critic
Test::Pod
Test::Pod::Coverage
Test::Pod::LinkCheck
Test::Portability::Files
Test::Refcount
Test::Requires
Test::Roo
Test::Script
Test::SharedFork
Test::Spec
Test::Spelling
Test::SubCalls
Test::TCP
Test::TempDir
Test::Tester
Test::Trap
Test::Version
Test::WWW::Mechanize
Test::WWW::Mechanize::Catalyst
Test::WWW::Mechanize::PSGI
Test::Warn
Test::Warnings
Test::Without::Module
Test::postgresql
Test::use::ok
Test::utf8
Text::Autoformat
Text::Brew
Text::Clip
Text::Diff
Text::German
Text::Glob
Text::MicroTemplate
Text::Reform
Text::SimpleTable
Text::Template
Text::Unidecode
Throwable
Throwable::Factory
Tie::IxHash
Tie::ToObject
Time::Duration
Time::Duration::Parse
Time::Warp
Tree::DAG_Node
Tree::Simple
Tree::Simple::VisitorFactory
Try::Tiny
Twiggy
Type::Tiny
Types::Serialiser
UNIVERSAL::can
UNIVERSAL::isa
UNIVERSAL::require
URI
URI::FromHash
UUID::Tiny
Variable::Magic
Version::Next
WWW::Mechanize
WWW::RobotRules
Want
XML::DOM
XML::LibXML
XML::NamespaceSupport
XML::Parser
XML::RegExp
XML::SAX
XML::SAX::Base
XML::Twig
XML::Writer
YAML
YAML::LibYAML
YAML::Syck
YAML::Tiny
aliased
asa
autobox
autobox::Core
autodie
bareword::filehandles
boolean
common::sense
constant::defer
indirect
lexical::underscore
local::lib
multidimensional
namespace::autoclean
namespace::clean
strictures
syntax
);
 
my @no_man = qw/-D man1dir=none -D man3dir=none/;
my $ccversion = qx{cc -V 2>&1}; chomp $ccversion;
my @solaris_args =
           ( qw(-DCC=cc ), qq(-Dccversion=\"${ccversion}\"),
             qw(-Dusedtrace -Duse64bitint -Duse64bitall
                -Dsed=/usr/bin/gsed
                -Duselargefiles -Doptimize=-xO3
                -n ) );

# install perl
system( qw/perlbrew install/, @dist,
        qw/--as/, $as, $perl, @threads,
        @no_man, @solaris_args, @args );

# Lock it down
# system( qw/chmod -R a-w/, "$ENV{HOME}/perl5/perlbrew/perls/$as" );
 
# give us a local::lib for installing things
system( qw/perlbrew lib create/, $lib );
 
# let's avoid any pod tests when we try to install stuff
system( qw/perlbrew exec --with/, $lib,
        qw/cpanm -v --mirror-only --mirror/, "http://localhost:3111/",
        qw/TAP::Harness::Restricted/ );
local $ENV{HARNESS_SUBCLASS} = "TAP::Harness::Restricted";

# Install the necessary modules used in module installation activities
# so we use them for all subsequent module installs.
# This is effectively bootstrapping.

system( qw/perlbrew exec --with/, $lib,
        qw/cpanm -v --mirror-only --mirror/, "http://localhost:3111/",
        qw/ ExtUtils::MakeMaker
            ExtUtils::Install
            Module::Build
            Module::Runtime
            List::Util
          / );

# some things need forcing
system( qw/perlbrew exec --with/, $lib,
        qw/cpanm -f -v --mirror-only --mirror/, "http://localhost:3111/",
        @problem_modules );
 
# now install the rest
system( qw/perlbrew exec --with/, $lib,
        qw/cpanm -v --mirror-only --mirror/, "http://localhost:3111/",
        @to_install );

# repeat to catch any circularity problems
system( qw/perlbrew exec --with/, $lib,
        qw/cpanm -v --mirror-only --mirror/, "http://localhost:3111/",
        @to_install );
